/* Fuzzy inference system generated by qfiscgen.m for the qFIS engine*/
/* Generated : 03-Apr-2025 17:11:49 */
/* MATLAB Version: 9.14.0.2337262 (R2023a) Update 5 */
/* Note: Based on the qFIS engine from https://github.com/kmilo17pet/qlibs */

#ifndef FIS_EMS3INPUTS_FIS_H
#define FIS_EMS3INPUTS_FIS_H

#ifdef __cplusplus
    extern "C" {
#endif

    void fis_EMS3inputs_init( void );
    void fis_EMS3inputs_run( float *inputs, float *outputs );

#ifdef __cplusplus
    }
#endif

#endif /* FIS_EMS3INPUTS_FIS_H */
