/* Fuzzy inference system generated by qfiscgen.m for the qFIS engine*/
/* Generated : 04-Apr-2025 18:38:15 */
/* MATLAB Version: 9.14.0.2337262 (R2023a) Update 5 */
/* Note: Based on the qFIS engine from https://github.com/kmilo17pet/qlibs */

#include "fis_EMS3inputs_fis.h"
#include "qfis.h"

/* FIS Object */
static qFIS_t fis_EMS3inputs;
/* I/O Fuzzy Objects */
static qFIS_Input_t fis_EMS3inputs_inputs[ 3 ];
static qFIS_Output_t fis_EMS3inputs_outputs[ 1 ];
/* I/O Membership Objects */
static qFIS_MF_t MFin[ 11 ], MFout[ 5 ];
/* I/O Names */
enum { power_reference, SoC, V_sc };
enum { P_ref_command };
/* I/O Membership functions tags */
enum { power_reference_Med_Deficit, power_reference_Low_Deficit, power_reference_Low_Surplus, power_reference_Med_Surplus, power_reference_Balanced, SoC_low, SoC_medium, SoC_high, V_sc_low, V_sc_medium, V_sc_high };
enum { P_ref_command_charge_SC, P_ref_command_discharge_SC, P_ref_command_off, P_ref_command_charge_Bat, P_ref_command_discharge_Bat };
/* Rules of the inference system */
static const qFIS_Rules_t rules[] = { 
    QFIS_RULES_BEGIN
       IF power_reference IS power_reference_Med_Deficit AND SoC IS SoC_low AND V_sc IS V_sc_low THEN P_ref_command IS P_ref_command_off END
       IF power_reference IS power_reference_Med_Deficit AND SoC IS SoC_low AND V_sc IS V_sc_medium THEN P_ref_command IS P_ref_command_discharge_SC END
       IF power_reference IS power_reference_Med_Deficit AND SoC IS SoC_low AND V_sc IS V_sc_high THEN P_ref_command IS P_ref_command_discharge_SC END
       IF power_reference IS power_reference_Med_Deficit AND SoC IS SoC_medium AND V_sc IS V_sc_low THEN P_ref_command IS P_ref_command_discharge_Bat END
       IF power_reference IS power_reference_Med_Deficit AND SoC IS SoC_medium AND V_sc IS V_sc_medium THEN P_ref_command IS P_ref_command_discharge_Bat END
       IF power_reference IS power_reference_Med_Deficit AND SoC IS SoC_medium AND V_sc IS V_sc_medium THEN P_ref_command IS P_ref_command_discharge_SC END
       IF power_reference IS power_reference_Med_Deficit AND SoC IS SoC_medium AND V_sc IS V_sc_high THEN P_ref_command IS P_ref_command_discharge_SC END
       IF power_reference IS power_reference_Med_Deficit AND SoC IS SoC_high AND V_sc IS V_sc_low THEN P_ref_command IS P_ref_command_discharge_Bat END
       IF power_reference IS power_reference_Med_Deficit AND SoC IS SoC_high AND V_sc IS V_sc_medium THEN P_ref_command IS P_ref_command_discharge_Bat END
       IF power_reference IS power_reference_Med_Deficit AND SoC IS SoC_high AND V_sc IS V_sc_high THEN P_ref_command IS P_ref_command_discharge_Bat END
       IF power_reference IS power_reference_Med_Deficit AND SoC IS SoC_high AND V_sc IS V_sc_high THEN P_ref_command IS P_ref_command_discharge_SC END
       IF power_reference IS power_reference_Low_Deficit AND SoC IS SoC_low AND V_sc IS V_sc_low THEN P_ref_command IS P_ref_command_off END
       IF power_reference IS power_reference_Low_Deficit AND SoC IS SoC_low AND V_sc IS V_sc_medium THEN P_ref_command IS P_ref_command_discharge_SC END
       IF power_reference IS power_reference_Low_Deficit AND SoC IS SoC_low AND V_sc IS V_sc_high THEN P_ref_command IS P_ref_command_discharge_SC END
       IF power_reference IS power_reference_Low_Deficit AND SoC IS SoC_medium AND V_sc IS V_sc_low THEN P_ref_command IS P_ref_command_discharge_Bat END
       IF power_reference IS power_reference_Low_Deficit AND SoC IS SoC_medium AND V_sc IS V_sc_medium THEN P_ref_command IS P_ref_command_discharge_SC END
       IF power_reference IS power_reference_Low_Deficit AND SoC IS SoC_medium AND V_sc IS V_sc_high THEN P_ref_command IS P_ref_command_discharge_SC END
       IF power_reference IS power_reference_Low_Deficit AND SoC IS SoC_high AND V_sc IS V_sc_low THEN P_ref_command IS P_ref_command_discharge_Bat END
       IF power_reference IS power_reference_Low_Deficit AND SoC IS SoC_high AND V_sc IS V_sc_medium THEN P_ref_command IS P_ref_command_discharge_SC END
       IF power_reference IS power_reference_Low_Deficit AND SoC IS SoC_high AND V_sc IS V_sc_high THEN P_ref_command IS P_ref_command_discharge_SC END
       IF power_reference IS power_reference_Balanced THEN P_ref_command IS P_ref_command_off END
       IF power_reference IS power_reference_Low_Surplus AND SoC IS SoC_low AND V_sc IS V_sc_low THEN P_ref_command IS P_ref_command_charge_SC END
       IF power_reference IS power_reference_Low_Surplus AND SoC IS SoC_low AND V_sc IS V_sc_medium THEN P_ref_command IS P_ref_command_charge_SC END
       IF power_reference IS power_reference_Low_Surplus AND SoC IS SoC_low AND V_sc IS V_sc_high THEN P_ref_command IS P_ref_command_charge_Bat END
       IF power_reference IS power_reference_Low_Surplus AND SoC IS SoC_medium AND V_sc IS V_sc_low THEN P_ref_command IS P_ref_command_charge_SC END
       IF power_reference IS power_reference_Low_Surplus AND SoC IS SoC_medium AND V_sc IS V_sc_medium THEN P_ref_command IS P_ref_command_charge_SC END
       IF power_reference IS power_reference_Low_Surplus AND SoC IS SoC_medium AND V_sc IS V_sc_high THEN P_ref_command IS P_ref_command_charge_Bat END
       IF power_reference IS power_reference_Low_Surplus AND SoC IS SoC_high AND V_sc IS V_sc_low THEN P_ref_command IS P_ref_command_charge_SC END
       IF power_reference IS power_reference_Low_Surplus AND SoC IS SoC_high AND V_sc IS V_sc_medium THEN P_ref_command IS P_ref_command_charge_SC END
       IF power_reference IS power_reference_Low_Surplus AND SoC IS SoC_high AND V_sc IS V_sc_high THEN P_ref_command IS P_ref_command_off END
       IF power_reference IS power_reference_Med_Surplus AND SoC IS SoC_low AND V_sc IS V_sc_low THEN P_ref_command IS P_ref_command_charge_SC END
       IF power_reference IS power_reference_Med_Surplus AND SoC IS SoC_low AND V_sc IS V_sc_low THEN P_ref_command IS P_ref_command_charge_Bat END
       IF power_reference IS power_reference_Med_Surplus AND SoC IS SoC_low AND V_sc IS V_sc_medium THEN P_ref_command IS P_ref_command_charge_Bat END
       IF power_reference IS power_reference_Med_Surplus AND SoC IS SoC_low AND V_sc IS V_sc_high THEN P_ref_command IS P_ref_command_charge_Bat END
       IF power_reference IS power_reference_Med_Surplus AND SoC IS SoC_medium AND V_sc IS V_sc_low THEN P_ref_command IS P_ref_command_charge_SC END
       IF power_reference IS power_reference_Med_Surplus AND SoC IS SoC_medium AND V_sc IS V_sc_medium THEN P_ref_command IS P_ref_command_charge_SC END
       IF power_reference IS power_reference_Med_Surplus AND SoC IS SoC_medium AND V_sc IS V_sc_medium THEN P_ref_command IS P_ref_command_charge_Bat END
       IF power_reference IS power_reference_Med_Surplus AND SoC IS SoC_medium AND V_sc IS V_sc_high THEN P_ref_command IS P_ref_command_charge_Bat END
       IF power_reference IS power_reference_Med_Surplus AND SoC IS SoC_high AND V_sc IS V_sc_low THEN P_ref_command IS P_ref_command_charge_SC END
       IF power_reference IS power_reference_Med_Surplus AND SoC IS SoC_high AND V_sc IS V_sc_medium THEN P_ref_command IS P_ref_command_charge_SC END
       IF power_reference IS power_reference_Med_Surplus AND SoC IS SoC_high AND V_sc IS V_sc_high THEN P_ref_command IS P_ref_command_off END
    QFIS_RULES_END
};
/* Rule strengths */
float rStrength[ 41 ] = { 0.0f };
/* Rule weighs */
static float ruleWeights[] = { 1.00f, 1.00f, 1.00f, 1.00f, 0.50f, 0.50f, 1.00f, 1.00f, 1.00f, 1.00f, 1.00f, 1.00f, 1.00f, 1.00f, 1.00f, 0.50f, 1.00f, 1.00f, 1.00f, 1.00f, 1.00f, 1.00f, 1.00f, 1.00f, 1.00f, 0.50f, 1.00f, 1.00f, 1.00f, 1.00f, 1.00f, 1.00f, 1.00f, 1.00f, 1.00f, 0.50f, 0.50f, 1.00f, 1.00f, 1.00f, 1.00f };


/* Parameters of the membership functions */
//static const float power_reference_Med_Deficit_p[] = { -0.0025f, -4000.0000f };
static const float power_reference_Med_Deficit_p[] = { -9000.0000f, -9000.0000f, -5000.0000f, -2000.0000f };
static const float power_reference_Low_Deficit_p[] = { -2500.0000f, -1500.0000f, -20.0000f };
static const float power_reference_Low_Surplus_p[] = { 20.0000f, 1500.0000f, 2500.0000f };
//static const float power_reference_Med_Surplus_p[] = { 0.0025f, 4000.0000f };
static const float power_reference_Med_Surplus_p[] = { 2000.0000f, 5000.0000f, 9000.0000f, 9000.0000f };
static const float power_reference_Balanced_p[] = { -25.0000f, 0.0000f, 25.0000f };
static const float SoC_low_p[] = { -1.7084f, 20.0000f };
static const float SoC_medium_p[] = { 20.0000f, 55.0000f, 90.0000f };
static const float SoC_high_p[] = { 1.3456f, 90.0000f };

//static const float V_sc_low_p[] = { -0.5731f, 200.0000f };
//static const float V_sc_low_p[] = { -0.0630f, 150.0000f };
static const float V_sc_low_p[] = { -0.0618f, 140.0000f };
//static const float V_sc_medium_p[] = { 205.0000f, 240.0000f, 310.0000f };
static const float V_sc_medium_p[] = { 18.2253f, 250.0000f };
//static const float V_sc_high_p[] = { 0.2461f, 320.0000f };
//static const float V_sc_high_p[] = { 0.0983f, 320.0000f };
static const float V_sc_high_p[] = { 0.0983f, 340.0000f };

static const float P_ref_command_charge_SC_p[] = { 0.3000f, 0.6000f, 1.3000f, 2.3000f };
static const float P_ref_command_discharge_SC_p[] = { -2.3000f, -1.3000f, -0.6000f, -0.3000f };
static const float P_ref_command_off_p[] = { -0.3000f, 0.0000f, 0.3000f };
static const float P_ref_command_charge_Bat_p[] = { 1.3000f, 2.3000f, 3.3000f, 3.3000f };
static const float P_ref_command_discharge_Bat_p[] = { -3.3000f, -3.3000f, -2.3000f, -1.3000f };

void fis_EMS3inputs_init( void ){
    /* Set inputs */
    qFIS_InputSetup( fis_EMS3inputs_inputs, power_reference, -9000.0000f, 9000.0000f );
    qFIS_InputSetup( fis_EMS3inputs_inputs, SoC, 0.0000f, 100.0000f );
    qFIS_InputSetup( fis_EMS3inputs_inputs, V_sc, 0.0000f, 350.0000f );
    /* Set outputs */
    qFIS_OutputSetup( fis_EMS3inputs_outputs, P_ref_command, -3.3000f, 3.3000f );
    /* Set membership functions for the inputs */
//    qFIS_SetMF( MFin, power_reference, power_reference_Med_Deficit, sigmf, NULL, power_reference_Med_Deficit_p, 1.0f );
    qFIS_SetMF( MFin, power_reference, power_reference_Med_Deficit, trapmf, NULL, power_reference_Med_Deficit_p, 1.0f );
    qFIS_SetMF( MFin, power_reference, power_reference_Low_Deficit, trimf, NULL, power_reference_Low_Deficit_p, 1.0f );
    qFIS_SetMF( MFin, power_reference, power_reference_Low_Surplus, trimf, NULL, power_reference_Low_Surplus_p, 1.0f );
//    qFIS_SetMF( MFin, power_reference, power_reference_Med_Surplus, sigmf, NULL, power_reference_Med_Surplus_p, 1.0f );
    qFIS_SetMF( MFin, power_reference, power_reference_Med_Surplus, trapmf, NULL, power_reference_Med_Surplus_p, 1.0f );
    qFIS_SetMF( MFin, power_reference, power_reference_Balanced, trimf, NULL, power_reference_Balanced_p, 1.0f );
    qFIS_SetMF( MFin, SoC, SoC_low, sigmf, NULL, SoC_low_p, 1.0f );
    qFIS_SetMF( MFin, SoC, SoC_medium, trimf, NULL, SoC_medium_p, 1.0f );
    qFIS_SetMF( MFin, SoC, SoC_high, sigmf, NULL, SoC_high_p, 1.0f );
//    qFIS_SetMF( MFin, V_sc, V_sc_low, sigmf, NULL, V_sc_low_p, 1.0f );
//    qFIS_SetMF( MFin, V_sc, V_sc_medium, trimf, NULL, V_sc_medium_p, 1.0f );
//    qFIS_SetMF( MFin, V_sc, V_sc_high, sigmf, NULL, V_sc_high_p, 1.0f );
    qFIS_SetMF( MFin, V_sc, V_sc_low, sigmf, NULL, V_sc_low_p, 1.0f );
    qFIS_SetMF( MFin, V_sc, V_sc_medium, gaussmf, NULL, V_sc_medium_p, 1.0f );
    qFIS_SetMF( MFin, V_sc, V_sc_high, sigmf, NULL, V_sc_high_p, 1.0f );
    /* Set membership functions for the outputs */
    qFIS_SetMF( MFout, P_ref_command, P_ref_command_charge_SC, trapmf, NULL, P_ref_command_charge_SC_p, 1.0f );
    qFIS_SetMF( MFout, P_ref_command, P_ref_command_discharge_SC, trapmf, NULL, P_ref_command_discharge_SC_p, 1.0f );
    qFIS_SetMF( MFout, P_ref_command, P_ref_command_off, trimf, NULL, P_ref_command_off_p, 1.0f );
    qFIS_SetMF( MFout, P_ref_command, P_ref_command_charge_Bat, trapmf, NULL, P_ref_command_charge_Bat_p, 1.0f );
    qFIS_SetMF( MFout, P_ref_command, P_ref_command_discharge_Bat, trapmf, NULL, P_ref_command_discharge_Bat_p, 1.0f );

    /* Configure the Inference System */
    qFIS_Setup( &fis_EMS3inputs, Mamdani,
                fis_EMS3inputs_inputs, sizeof(fis_EMS3inputs_inputs),
                fis_EMS3inputs_outputs, sizeof(fis_EMS3inputs_outputs),
                MFin, sizeof(MFin), MFout, sizeof(MFout),
                rules, rStrength, 41u );
    qFIS_SetRuleWeights( &fis_EMS3inputs, ruleWeights );
}

void fis_EMS3inputs_run( float *inputs, float *outputs ) {
    /* Set the crips inputs */
    qFIS_SetInput( fis_EMS3inputs_inputs, power_reference, inputs[ power_reference ] );
    qFIS_SetInput( fis_EMS3inputs_inputs, SoC, inputs[ SoC ] );
    qFIS_SetInput( fis_EMS3inputs_inputs, V_sc, inputs[ V_sc ] );

    qFIS_Fuzzify( &fis_EMS3inputs );
    if ( qFIS_Inference( &fis_EMS3inputs ) > 0 ) {
        qFIS_DeFuzzify( &fis_EMS3inputs );
    }
    else {
        /* Error! */
    }

    /* Get the crips outputs */
    outputs[ P_ref_command ] = qFIS_GetOutput( fis_EMS3inputs_outputs, P_ref_command );
}
